### ISSUE TITLE
Prediction.py not compatible with the model (missing 4 required positional arguements)

### ISSUE THREAD

**Issue by SinuoWang** [TRUMANCFY/SLIM#3]
Hi all,

When I run the prediction code, There's always an error of "forward() missing 4 required positional arguments: 'intent_token_ids', 'B_tag_mask', 'BI_tag_mask', and 'tag_intent_label". 

However, I believe these variables works as labels and shouldn't be fed into the model during inference. Does anyone know how to fix this? Thanks for your help in advance :)

**Comment by SinuoWang** [comment]
Hi, 

From my understanding of the code, to predict the slot-level intents of the non-padding slots requires the true labels so that we can have the correct position of the slot first, am I right?

Does this mean we also need the true labels even in the prediction.py file?

Cheers,

**Comment by swapnilg915** [comment]
@SinuoWang I am also facing the same issue. I tried putting None for the above 4 variables:

            inputs = {"input_ids": batch[0],
                      "attention_mask": batch[1],
                      "intent_label_ids": None,
                      "slot_labels_ids": None,
                      "intent_token_ids": None,
                      "B_tag_mask": None,
                      "BI_tag_mask": None,
                      "tag_intent_label": None}

but getting error

Traceback (most recent call last):
  File "predict.py", line 230, in <module>
    predict(pred_config)
  File "predict.py", line 168, in predict
    outputs = model(**inputs)
  File "/home/swapnil/anaconda3/lib/python3.7/site-packages/torch/nn/modules/module.py", line 1194, in _call_impl
    return forward_call(*input, **kwargs)
  File "/home/swapnil/Projects/SLIM/model/modeling_jointbertmultiintent.py", line 168, in forward
    tag_intent_vec = torch.einsum('bml,bld->bmd', BI_tag_mask, sequence_output)
  File "/home/swapnil/anaconda3/lib/python3.7/site-packages/torch/functional.py", line 378, in einsum
    return _VF.einsum(equation, operands)  # type: ignore[attr-defined]
TypeError: expected Tensor as element 0 in argument 1, but got NoneType


Let me know once you fix it
